In [2]:
import torch
from torch import nn
from torch.nn import init
net = nn.Sequential(nn.Linear(4, 3), nn.ReLU(), nn.Linear(3, 1))
#pytorch已进⾏默认初始化
print(net)
X = torch.rand(2, 4)
Y = net(X).sum()

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [3]:
Y

tensor(0.3679, grad_fn=<SumBackward0>)

In [9]:
for name, param in net.named_parameters():
    print(name)
    print(param)
    print("*"*30)

0.weight
Parameter containing:
tensor([[ 0.4420,  0.3928, -0.1166,  0.4410],
        [ 0.4816, -0.4433, -0.2807,  0.0370],
        [-0.1635, -0.2811, -0.3569, -0.0320]], requires_grad=True)
******************************
0.bias
Parameter containing:
tensor([-0.2356, -0.1315, -0.4440], requires_grad=True)
******************************
2.weight
Parameter containing:
tensor([[ 0.3550,  0.3306, -0.0632]], requires_grad=True)
******************************
2.bias
Parameter containing:
tensor([0.0446], requires_grad=True)
******************************


In [11]:
[*net.parameters()]

[Parameter containing:
 tensor([[ 0.4420,  0.3928, -0.1166,  0.4410],
         [ 0.4816, -0.4433, -0.2807,  0.0370],
         [-0.1635, -0.2811, -0.3569, -0.0320]], requires_grad=True),
 Parameter containing:
 tensor([-0.2356, -0.1315, -0.4440], requires_grad=True),
 Parameter containing:
 tensor([[ 0.3550,  0.3306, -0.0632]], requires_grad=True),
 Parameter containing:
 tensor([0.0446], requires_grad=True)]

In [14]:
net[0]

Linear(in_features=4, out_features=3, bias=True)

In [16]:
class MyModel(nn.Module):
    def __init__(self, **kwargs):
        super(MyModel, self).__init__(**kwargs)
        self.weight1 = nn.Parameter(torch.rand(20, 20))
        self.weight2 = torch.rand(20, 20)
    def forward(self, x):
        pass
    
n = MyModel()
for name, param in n.named_parameters():
    print(name)

weight1


In [29]:
weight = list(net[0].parameters())[0]

In [30]:
weight.data

tensor([[ 0.4420,  0.3928, -0.1166,  0.4410],
        [ 0.4816, -0.4433, -0.2807,  0.0370],
        [-0.1635, -0.2811, -0.3569, -0.0320]])

In [32]:
print(weight.grad)

None


In [33]:
Y.backward()

In [34]:
weight.grad

tensor([[0.2612, 0.3837, 0.2039, 0.3590],
        [0.2327, 0.0487, 0.0209, 0.1109],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [40]:
# 初始化参数
for name, param in net.named_parameters():
    print(name)
    if "weight" in name:
        init.normal_(param,mean=0, std=0.01)

0.weight
0.bias
2.weight
2.bias


In [39]:
[*net.parameters()]

[Parameter containing:
 tensor([[-0.0281,  0.0175, -0.0054,  0.0080],
         [ 0.0003,  0.0010, -0.0089, -0.0048],
         [-0.0025, -0.0085,  0.0057,  0.0056]], requires_grad=True),
 Parameter containing:
 tensor([-0.2356, -0.1315, -0.4440], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0202, -0.0078,  0.0063]], requires_grad=True),
 Parameter containing:
 tensor([0.0446], requires_grad=True)]

In [41]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)
net = MLP()
net.state_dict()

OrderedDict([('hidden.weight', tensor([[-0.4427,  0.1756, -0.1313],
                      [-0.3830,  0.4025, -0.3399]])),
             ('hidden.bias', tensor([0.3250, 0.3961])),
             ('output.weight', tensor([[0.0754, 0.4948]])),
             ('output.bias', tensor([-0.2686]))])

In [44]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001,
momentum=0.9)
optimizer.state_dict()

{'param_groups': [{'dampening': 0,
   'lr': 0.001,
   'momentum': 0.9,
   'nesterov': False,
   'params': [139685872666016,
    139685872666160,
    139685872666232,
    139685872666304],
   'weight_decay': 0}],
 'state': {}}

In [46]:
torch.cuda.get_device_capability()

(5, 0)

In [47]:
torch.cuda.get_device_name()

'GeForce GTX 950M'

In [50]:
torch.cuda.get_device_properties(0)

_CudaDeviceProperties(name='GeForce GTX 950M', major=5, minor=0, total_memory=2004MB, multi_processor_count=5)